### ISSUE TITLE
Exceptions when using shop and bettershop commands with no argument

### ISSUE THREAD

**Issue by Klawdek** [Huskehhh/BetterShop#1]
**Describe the bug**
When entering the commands shop or bettershop with no argument is throws the following exception:
https://pastebin.com/20tx51CQ

**To Reproduce**
Do /shop with no argument 
**Expected behavior**
Either something opens up or a message in chat about the missing argument. 
**Screenshots**

**Additional context**
I am using build 21, minecraft 1.16.2 with paper 184.   I had this setup already for testing some other things and it already had essentials, vault and citizens.  Maybe I should set up a new one with 1.16.4 and the latest paper?
This is where it gets weird.  When this first occurred after causing the above error the plugin seemed to become unstable. It would work for a few transactions and then nothing would happen when I clicked on an item to buy it and an exception was thrown.   I stopped and restarted the server 3 or 4 times and each time the shop worked before I caused the above error but after causing it the plugin would work for a short time and then do as I just described.  I had some distractions and I was getting tired.  So I decided to work on it the next day and duplicate all the results to be sure I had all the info for the report   The next day I started the test server and I could not get into the plugin at all.  It was throwing exceptions even though I typed shop with the nameOfShop argument.  I stopped and started the server a few times and this happened each time.  I then renamed the BetterShop directory to preserve the shop files as they might be corrupted and new files were generated. After that I was able to get the above error but I have not been able to duplicate the rest of it.

**Comment by Huskehhh** [comment]
Thanks for the issue!

Can you confirm that your config (plugins/BetterShop/config.yml) has a 'default-shop' that exists?

**Comment by Klawdek** [comment]
the config has this line:
default-shop: "MAIN"
The rest is the comments at the beginning.
There where no shops configured in the shops directory by default.  That directory is empty until I create a shop.
I created a shop named MAIN (it is case sensitive) and then when I type /shop it opens.
