### ISSUE TITLE
When close upon transaction false it stays in window that item amount is entered.  It should go back to items page

### ISSUE THREAD

**Issue by Klawdek** [Huskehhh/BetterShop#11]
**Is your feature request related to a problem? Please describe.**
When Close upon transaction is false, after a purchase it stays in the window where the amount is to buy or sell is enetered.  I think it should go back to previous window where the items are listed.  
**Describe the solution you'd like**
After a transaction it should go back to the window that has the items to buy or sell rather than staying on the window where amounts to buy or sell are entered.

**Additional context**
I am also not sure if this should be a per item config option.  Maybe per page or global.  If it is difficult to change then maybe a global config option to set the default to true or false.

This is the screen it stays on after transaction:
![Screenshot (1459)](https://user-images.githubusercontent.com/45950944/99611786-ee71a780-29d9-11eb-9cc9-156b3154a534.png)

It should go back to this one:
![Screenshot (1460)](https://user-images.githubusercontent.com/45950944/99611810-f9c4d300-29d9-11eb-92d3-5f07c4a33492.png)

**Comment by Huskehhh** [comment]
This has been implemented https://github.com/Huskehhh/BetterShop/commit/b13a90e399276d93f0989e7d6405da1ff737d0db

Items set to close on transaction will go back to the previous GUI (in this case, it will go back to the shop display)
