### ISSUE TITLE
Item Display name and lore does not show up in shop. Item display name cannot be reset.

### ISSUE THREAD

**Issue by Klawdek** [Huskehhh/BetterShop#12]
**Describe the bug**
The Item display name and lore shows up when you are in edit mode but not when using the shop.  Also the instructions for adding and removing lore is not present (Left click to add, right click to remove).  Right-click works to remove lore but not the item display name.
**To Reproduce**
1. Set item display name and lore and notice that the instructions for adding and removing are not there.
2. Go into shop like you where buying or selling something
3. See that the display and lore do not show up

**Expected behavior**
The instructions shouold be there and the item displayname and the lore should show when using shop.
**Screenshots**

**Additional context**
Here is what the instructions in the old program looked like:
![Screenshot (1461)](https://user-images.githubusercontent.com/45950944/99614896-0c420b00-29e0-11eb-9a08-faecd0eea809.png)
![Screenshot (1462)](https://user-images.githubusercontent.com/45950944/99614904-0fd59200-29e0-11eb-8f56-f0064dd3e036.png)

**Comment by Huskehhh** [comment]
Fixed!
