### ISSUE TITLE
After joining server player can get buy and sell one item with no charge.

### ISSUE THREAD

**Issue by Klawdek** [Huskehhh/BetterShop#13]
**Describe the bug**
After joining server player can buy an item and is not charged.  If they sell an item they get no money. 
I have the buy items and sell items on different pages.  This just happens on the first transaction on the page after the player joins the server.
**To Reproduce**
1. Join the server.
2. Check balance.
3. Buy item and see there is no charge.
4. Buy another item and see that you are charged for it.
**Expected behavior**
To be charged for items bought and to get the money for items sold.
**Screenshots**
![Screenshot (1465)](https://user-images.githubusercontent.com/45950944/99620572-6a282000-29eb-11eb-9b54-4c88869e3d80.png)

**Additional context**

**Comment by Huskehhh** [comment]
Fixed!

It did charge users, it just displayed their balance wrong!
