### ISSUE TITLE
Rewording sell and buy items in the editing items gui

### ISSUE THREAD

**Issue by Klawdek** [Huskehhh/BetterShop#14]
**Is your feature request related to a problem? Please describe.**
The wording could be more clear on the buy and sell items in the editing item gui where the function and buy and sell prices are set.
**Describe the solution you'd like**
The present wording for the sell item (diamond) is:
Change sell cost
Sell: 0
The present wording for the buy item (gold bar) is:
Change cost
Cost: 0

I think it should be changed to
Sell Item:
Change sell price
Sell price: 0

Buy Item:
Change buy price
Buy price: 0

**Additional context**
Here are the menu items I am talking about:
![Screenshot (1467)](https://user-images.githubusercontent.com/45950944/99624293-a495bb00-29f3-11eb-913d-ec99f6c4c488.png)

![Screenshot (1468)](https://user-images.githubusercontent.com/45950944/99624310-af505000-29f3-11eb-8086-0583b3f9bc96.png)

**Comment by Huskehhh** [comment]
Fixed!
