### ISSUE TITLE
Item amount in edit display items does not work 

### ISSUE THREAD

**Issue by Klawdek** [Huskehhh/BetterShop#15]
**Describe the bug**
When the item amount is set in the edit items display gui.  It has no effect nor does it show when items displayed in shop.
**To Reproduce**
1. Change item display number to some number more than 1 like 32.
2. Go into shop and look at item and see that it is still just one item and not 32.
3. Purchase item and see that 32 show up in the gui to set amount you want to buy, but when buying it is still just one at a time.

**Expected behavior**
Not sure about this feature at all.  I think it is meant to allow for the buying of items in specific amounts (like 32)
**Screenshots**
Here the item amount is set to 32
![Screenshot (1470)](https://user-images.githubusercontent.com/45950944/99752448-f731ae80-2aa9-11eb-8db7-95688f999e62.png)

It shows up in the gui when in edit mode
![Screenshot (1471)](https://user-images.githubusercontent.com/45950944/99752490-09abe800-2aaa-11eb-9cbd-d6a7c07b4d35.png)

When you go to buy item it does not show up
![Screenshot (1472)](https://user-images.githubusercontent.com/45950944/99752532-20523f00-2aaa-11eb-8fc4-5b95bdaef50b.png)

On this screen where you set amount to buy it shows up
![Screenshot (1473)](https://user-images.githubusercontent.com/45950944/99752609-411a9480-2aaa-11eb-8f8e-b6475b98baef.png)

When you buy select to buy 1 it gives you just 1.  I think it is supposed to give you 1 half stack of 32.
**Additional context**
Not sure the use of this feature.  However I have seen shops on servers that were buying and selling items in certain amounts.
I think if the feature is going to be in then it should work and we need to figure out how it is supposed to work.

**Comment by Huskehhh** [comment]
Tbh this feature doesn't even seem necessary at all. I *think* it was purely for display in the previous plugin?
I'm just gonna remove this feature entirely...

**Comment by Klawdek** [comment]
It actually does work in the old plugin.  Not sure how useful a feature it is.

**Comment by Huskehhh** [comment]
Yeah okay, just seems redundant as users can edit how much of an item they want to buy fairly easily as is.
