### ISSUE TITLE
Adding and removing items from pages not working properly

### ISSUE THREAD

**Issue by Klawdek** [Huskehhh/BetterShop#2]
**Describe the bug**
When in shop edit mode, either left or right clicking an item in inventory it will prompt to put item in slot in the shop.
After doing that only right click will allow you to go to the "editing item" screen. After coming out of that screen back to the shop page the top of the gui says "Now select the new slot."  Right or left clicking on any slot will place another item there.
It is not leaving the place item mode.
Also right or left clicking item in store slot takes you to item edit mode which means items cannot be removed from store slots.

**To Reproduce**
1. Enter shop edit mode.
2. Click on item in inventory and then click on slot on page.
3. Then try left clicking item you just placed and note that nothing happens.
4. Right click and it will enter edit item page.
5.  Exit edit item page and not that it now says "Now select the new slot"
6.  CLick on an empty slot
7. Note that it places another item there (even if another one is not in inventory)
8.  Also try to remove an item from store slot by any means.

**Expected behavior**
In the original when you were in edit page, to put an item into the store page you had to right click item in inventory and
then right or left click on slot in store.   After that no more clicking on slots would add items until you clicked on another item in the inventory.  To remove an item from inventory you had to right click on an item in the store slot and then right or left click on an inventory slot.
Here it is entering item edit with a right click and doing nothing with left click.
Right clicking for moving items back and forth between store and inventory (also for moving items to different store slots) and left clicking to enter items properties gui (which you have labeled "item edit" in this version)
It should also leave item moving mode after moving item.

**Screenshots**

**Additional context**

**Comment by Huskehhh** [comment]
Thanks so much for your efforts mate, I really appreciate it.

I'll fix this tomorrow morning 👍
