### ISSUE TITLE
It is possible to add stacks and partial stacks to items that show up in edit menu and in the gui for specifying amount of items in transaction

### ISSUE THREAD

**Issue by Klawdek** [Huskehhh/BetterShop#21]
**Describe the bug**
When adding items to shop clicking on an item that is stacked in player inventory will place the stack into the shop.
The fact that there is n=more than one item in stack can be seen in editing gui and when player goes to specify the amount the wish to transact.
**To Reproduce**
1. Add item to shop page by clicking on item in your inventory that has more than one in the stack.
2. Notice that it can be seen in the editing gui.
3. Then try a transaction with that item and note that in the gui where the amount to transact is specified the amount in the stack shows up.

**Expected behavior**

**Screenshots**
Here is what it looks like in the editing menus:
![Screenshot (1522)](https://user-images.githubusercontent.com/45950944/100161042-51e65400-2e76-11eb-89b1-66c0dbbe4358.png)
![Screenshot (1523)](https://user-images.githubusercontent.com/45950944/100161064-5dd21600-2e76-11eb-97fd-f9892efdac51.png)
Here is what it looks like when players are buying an item:
![Screenshot (1524)](https://user-images.githubusercontent.com/45950944/100161096-6f1b2280-2e76-11eb-81ae-849cc4db1c9a.png)
![Screenshot (1525)](https://user-images.githubusercontent.com/45950944/100161113-73474000-2e76-11eb-8b97-4ebad4a3ea2d.png)

**Additional context**
I am not sure about the multiple item thing.  As we discussed before it seems redundant.  However some servers do use it.  I do not know why, however, I have found that other server owners seem to know things I don't.  At the very least we probably need to make sure that only one item can be put in shop and not stacks and partial stacks.  If we do allow that, then we would have to implement the feature of being able to transact in units of stacks and partial stacks.  
I also found on two occasions that even though I had only placed one item it somehow became two items.  This happened twice early on and I have not been able to duplicate it.

**Comment by Huskehhh** [comment]
The fix implemented will simply just place one of the itemstack the user has given, which should suffice given that users can specify how many items they want to buy.

Cheers!
