### ISSUE TITLE
When editing item and buy function is selected options to set both buy and sell prices show in gui

### ISSUE THREAD

**Issue by Klawdek** [Huskehhh/BetterShop#23]
**Describe the bug**
Both buy and sell prices show in editing items gui when buy function is selected.  When sell function is selected only the sell price is show.
This is not a big deal and it has always been like this, but it could be a bit confusing.
**To Reproduce**
1. Edit item to buy function and notice that options to set buy and sell price are displayed.
2. Change function to sell and notice only sell price is displayed.

**Expected behavior**
Only option to set buy price should be displayed when buy function is selected as it is with the sell function.
 
**Screenshots**
![Screenshot (1529)](https://user-images.githubusercontent.com/45950944/100165377-bce85880-2e7f-11eb-9de7-39232286a8b9.png)

**Additional context**

**Comment by Huskehhh** [comment]
Yeah. I was never sure if this was intended or not in the original, anywho. It has been removed!
