### ISSUE TITLE
New function to both buy and sell.

### ISSUE THREAD

**Issue by Klawdek** [Huskehhh/BetterShop#24]
**Is your feature request related to a problem? Please describe.**
It would be nice if in addition to buy only and sell only functions there was a buy and sell function.  This would be very useful as many items are both bought and sold.  It would make it easier for admins to set up and easier for players who can buy and sell from same gui screen rather than having to navigate between the same items in different slots or even pages one for buying and one for selling. 

**Describe the solution you'd like**
Add a new function that allows the item to be both bought and sold.  In this case of course there should be the option to set both buy and sell prices.
One of the servers I play on that uses shopgui+ has it set up with left-click on item to buy and right-click to sell.

**Additional context**

**Comment by Huskehhh** [comment]
Nice idea, I like it!
