### ISSUE TITLE
Does not charge correct amount when buying or selling

### ISSUE THREAD

**Issue by Klawdek** [Huskehhh/BetterShop#9]
**Describe the bug**
When items are bought and sold either no money is charged or only 1 is charged no matter what the price
**To Reproduce**
1. Check balance
2. Buy or sell something to shop
3. Check balance and note that it is not correct

**Expected behavior**
Correct charging for items
**Screenshots**

**Additional context**
Here is a screenshot.  This happens when buying or selling.
Also not that it just says the amount sold but not of what item.
![Screenshot (1458)](https://user-images.githubusercontent.com/45950944/99610940-58894d00-29d8-11eb-9580-11e8871b19c3.png)

**Comment by Huskehhh** [comment]
Damn! what a silly mistake from me!

This should be fixed now, thanks so much!

**Comment by Huskehhh** [comment]
jumped the gun on this, think i got the fix wrong
